---
eureka:
   client:
        serviceUrl:
            defaultZone:    http://localhost:8010/eureka
---
spring:
  profiles: subject
pronouns.words: I,You,He,She,It

---
spring:
  profiles: verb
pronouns.words: ran,knew,had,saw,bought

---
spring:
  profiles: article
pronouns.words: a,the

---
spring:
  profiles: adjective
pronouns.words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
pronouns.words: boat,book,vote,seat,backpack,partition,groundhog  

